[조재민] 3일차 문제 제출 (4796)
Woo-Yeol/2022-koreatech-algorithm-study pull request #12
Opened 2022-09-05 08:54 UTC by JaeMin98

가능한 캠핑 일 수를 연속하는 P일 중 L일동안 사용한 것을 a로 계산하고,
전체 휴가 수인 V를 P로 나눈 나머지에서 사용 가능한 일 수를 b로 계산하여 (a+b)를 출력

2022-09-05 12:07 UTC, zsmalla approved these changes
오 입력받음과 동시에 처리해서 반복문 사용을 줄인 것 좋은 것 같습니다. 문제에서 간과하기 쉬운 규칙도 잘 찾아낸 것 같아요! 저는 나머지 규칙에서 시간을 좀 많이 썼는디.. 굳이 지적을 하자면 읽는 사람의 입장에서 변수명에 의한 가독성인데, 문제 푸는 사람 입장에서는 크게 신경 쓰지 않으셔도 좋을 것 같습니다.

2022-09-06 00:23 UTC, Woo-Yeol requested changes

2022-09-06 00:23 UTC, Woo-Yeol commented on src/1주차/4796_python_조재민.py
> +        print("Case %d: %d" %(roop_count, a + b))
다음처럼 출력하면 입력받자마자 출력되지 않나요? 출력되지 않는다면 이유도 궁금합니다!

2022-09-07 11:03 UTC, honeyuheony approved these changes
저랑 거의 동일한 방법으로 접근하고, 변수에 미리 값을 할당해 코드가 깔끔한 것 좋습니다!

2022-09-08 14:50 UTC, JaeMin98 commented on src/1주차/4796_python_조재민.py
> +        print("Case %d: %d" %(roop_count, a + b))
입력 즉시 프린트 됩니다!

2022-09-12 06:14 UTC, Woo-Yeol approved these changes

2022-09-12 06:14 UTC, merged