[김우헌] 3일차 문제 제출(4796)
Woo-Yeol/2022-koreatech-algorithm-study pull request #16
Opened 2022-09-05 16:52 UTC by honeyuheony

eval 메소드를 통한 조건에 따른 변동값 출력

2022-09-06 00:28 UTC, Woo-Yeol requested changes
와 코드 수가 진짜 확 줄었네요 eval 을 사용하여서 이런식의 조건문을 넣을 수 있음을 처음 알았습니다. eval을 쓰지 않고 변수들로 연산에 넣게되면 연산이 안 이루어지나요?

2022-09-06 01:46 UTC, honeyuheony commented
> 와 코드 수가 진짜 확 줄었네요 eval 을 사용하여서 이런식의 조건문을 넣을 수 있음을 처음 알았습니다. eval을 쓰지 않고 변수들로 연산에 넣게되면 연산이 안 이루어지나요?

사실 이 문제 같은 경우에는 min (V % P, L)로 eval을 안쓰고 바로 계산할 수 있네요 ㅎㅎ
eval 내장함수를 통해서 조건문이나 복잡한 연산식, 함수 등의 연산값을 바로 출력할 수 있습니당

2022-09-07 00:13 UTC, Woo-Yeol approved these changes

2022-09-07 08:33 UTC, zsmalla approved these changes
eval활용해서 출력 코드를 깔끔하게 처리한 것 너무 좋은 아이디어인 것 같습니다!

2022-09-07 12:18 UTC, JaeMin98 approved these changes
eval 함수를 쓴 걸 보고 추가로 eval의 추가적인 활용법을 확인해보다 흥미로운 활용법도 찾았습니당

https://velog.io/@mickeyshoes/Python-eval-%ED%95%A8%EC%88%98%EB%A5%BC-%EC%95%84%EC%8B%9C%EB%82%98%EC%9A%94

요거 한번 보시죵

2022-09-08 01:40 UTC, merged