jisu day2 commit (10814)
Woo-Yeol/2022-koreatech-algorithm-study pull request #5
Opened 2022-09-02 05:19 UTC by zsmalla

input 정보와 가입한 순서를 튜플형태로 리스트에 저장해서 관리, 해당 리스트를 sorted메소드로 정렬해서 활용하되 우선순위는 lambda를 활용해서 나이 -> 가입한 순서로 정렬하도록 함

2022-09-02 14:24 UTC, JaeMin98 commented
입력순(시간순)으로 입력을 받아 lst에 저장을 하면 "sorted(lst, key = lambda x : (int(x[0][0]),x[1]))" 구문에서 x[1]은 생략해도 될 것 같슴다

2022-09-02 18:18 UTC, honeyuheony commented
리스트 내부 원소 개수가 많지 않으므로 튜플이 아닌 다른 리스트원소로 만들면 조금더 가독성이 좋지 않을까 하는 개인적인 생각이 들었습니다.
sorted함수를 통해 코드 길이를 줄인 것 좋습니다!

2022-09-05 01:12 UTC, Woo-Yeol requested changes
```
for l in sorted(lst, key = lambda x : (int(x[0][0]),x[1])):     # 정렬 : 우선순위 나이 -> 가입한 순서
     print(l[0][0], l[0][1])
```
가 어떻게 동작하는 것인지 이해가 잘 되지 않습니다.

추가적인 설명 요청드려도 괜찮을까요?

2022-09-05 07:50 UTC, honeyuheony approved these changes
리스트 내부 원소 개수가 많지 않으므로 튜플이 아닌 다른 리스트원소로 만들면 조금더 가독성이 좋지 않을까 하는 개인적인 생각이 들었습니다.
sorted함수를 통해 코드 길이를 줄인 것 좋습니다!

2022-09-05 11:22 UTC, zsmalla commented
> 리스트 내부 원소 개수가 많지 않으므로 튜플이 아닌 다른 리스트원소로 만들면 조금더 가독성이 좋지 않을까 하는 개인적인 생각이 들었습니다. sorted함수를 통해 코드 길이를 줄인 것 좋습니다!

지적 감사드립니당 sorted함수의 정렬 key에 lambda식으로 한 번에 하나의 리스트를 정렬하려다보니 이런 코드 형태가 나온 것 같습니다! 가독성도 고려 해봐야겠네여

2022-09-05 11:29 UTC, zsmalla commented
> ```
> for l in sorted(lst, key = lambda x : (int(x[0][0]),x[1])):     # 정렬 : 우선순위 나이 -> 가입한 순서
>      print(l[0][0], l[0][1])
> ```
> 
> 가 어떻게 동작하는 것인지 이해가 잘 되지 않습니다.
> 
> 추가적인 설명 요청드려도 괜찮을까요?

일단 sorted 함수의 첫번재 인자로 iterable한 컬렉션을 넣으면 정렬된 컬렉션이 반환이 되기 때문에 바로 for문에 적용 가능합니다 또, key 부분에 lambda x : (x[0], x[1]) 형태로 넣어주면 리스트 내부의 각 요소별 0번째 인덱스 순으로 정렬, 값이 같으면 다음 우선순위로 1번째 인덱스 순으로 정렬하는 형태입니다. 위 코드상 리스트의 원소로 ([나이, 이름], 가입한 순서)를 관리하므로 [0][0]인덱스는 나이, [1]인덱스는 가입 순서 순으로 정렬하는 것입니다

2022-09-05 11:32 UTC, zsmalla commented
> 입력순(시간순)으로 입력을 받아 lst에 저장을 하면 "sorted(lst, key = lambda x : (int(x[0][0]),x[1]))" 구문에서 x[1]은 생략해도 될 것 같슴다

시간순으로 입력을 받는 다는 게 잘 이해되지 않습니다. 하나씩 입력 받을 때 마다 자동으로 정렬하도록 구현하는 것인가요??

2022-09-06 00:12 UTC, Woo-Yeol commented
> > 입력순(시간순)으로 입력을 받아 lst에 저장을 하면 "sorted(lst, key = lambda x : (int(x[0][0]),x[1]))" 구문에서 x[1]은 생략해도 될 것 같슴다
> 
> 시간순으로 입력을 받는 다는 게 잘 이해되지 않습니다. 하나씩 입력 받을 때 마다 자동으로 정렬하도록 구현하는 것인가요??

제가 보기에는 리스트가 순서가 있는 배열이다보니 이미 리스트를 형성하는 순간 x[1] 가입 순서대로 정렬이 되어있어 굳이 한 번 더 정렬하지 않아도 괜찮다라는 것 같습니다

2022-09-06 00:12 UTC, Woo-Yeol approved these changes

2022-09-07 12:49 UTC, JaeMin98 approved these changes
입력순(시간순)으로 입력을 받아 lst에 저장을 하면 "sorted(lst, key = lambda x : (int(x[0][0]),x[1]))" 구문에서 x[1]은 생략해도 될 것 같슴다

2022-09-08 00:00 UTC, merged